name: ci

on:
  push:
    branches:
      - main

jobs:
  build-deploy-pages:
    name: Build GitHub Pages
    uses: ./.github/workflows/pages.yaml
    with:
      sitekey: nereineweb
      dist: ./nereineweb.github.io/dist
      deploy_branch: publish
      wipe_deploy_branch: true
      cname:
     
